### ISSUE TITLE
filtered results

### ISSUE THREAD

**Issue by me0ne0** [EvertonCa/SeleniumSemanticScraper#3]
Hi everton,
is there a way to filter results like 5 years filter? 

can i directly put the url in the search of Main.py instead of keyword ? e.g https://www.semanticscholar.org/search?year%5B0%5D=2014&year%5B1%5D=2019&q=malware&sort=relevance

thirdly, the results upto 200 pages, returns 2000 results max?

**Comment by EvertonCa** [comment]
Hello! For now, there is no way to filter the results by year!

You would have to modify the code inside SemanticScholarMetaCrawler.py to add you url, but it will require quite a lot lines to be modified.

200 pages will mean actually 600 pages (with some results been the same), so it would be around 6000 results. The problem is that excel has a lines limit. And you can see that there is a tab for the authors. And that tab will have a lot more than 6000 authors. This is where you will have the problem with that many pages.

Sorry for the late (a lot) reply. I did not received any notification about this message.
